### PR TITLE
Fix frozen string error when downloading CSV and streaming disabled

### LINKED ISSUE #7032: Freeze in CVBuilder error
### Did you find a bug?

In master, when you try to csv download a RuntimeError: can't modify frozen String happen
Line:
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/csv_builder.rb#L55 or
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/csv_builder.rb#L52 (if has byte_order_mark)

### Expected behavior

CSVBuilder work

### Actual behavior

RuntimeError: can't modify frozen String happen

### How to reproduce
Try to download a csv file from a index/table list or use CSVBuilder directly.

### LINKED ISSUE #7318: "FrozenError: can't modify frozen String" on CSV export
I get the following error when trying to export a CSV from an index table with version 2.10

Backtrace:
```
FrozenError: can't modify frozen String: ""
  from activeadmin (2.10.0) lib/active_admin/csv_builder.rb:55:in `build'
  from activeadmin (2.10.0) lib/active_admin/resource_controller/streaming.rb:27:in `stream_resource'
  from activeadmin (2.10.0) lib/active_admin/resource_controller/streaming.rb:40:in `stream_csv'
  from activeadmin (2.10.0) lib/active_admin/resource_controller/streaming.rb:14:in `block (2 levels) in index'
  from responders (3.0.1) lib/action_controller/responder.rb:238:in `default_render'
  from responders (3.0.1) lib/action_controller/responder.rb:190:in `to_format'
  from responders (3.0.1) lib/action_controller/responder.rb:165:in `respond'
  from responders (3.0.1) lib/action_controller/responder.rb:158:in `call'
  from responders (3.0.1) lib/action_controller/respond_with.rb:213:in `respond_with'
  from inherited_resources (1.13.1) lib/inherited_resources/actions.rb:7:in `index'
  from activeadmin (2.10.0) lib/active_admin/resource_controller/streaming.rb:13:in `index'
  from actionpack (6.1.4.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from actionpack (6.1.4.6) lib/abstract_controller/base.rb:228:in `process_action'
  from actionpack (6.1.4.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
  from actionpack (6.1.4.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from activesupport (6.1.4.6) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from actiontext (6.1.4.6) lib/action_text/rendering.rb:20:in `with_renderer'
  from actiontext (6.1.4.6) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
  from activesupport (6.1.4.6) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.4.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.4.6) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from actionpack (6.1.4.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
  from actionpack (6.1.4.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  from activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from sentry-rails (5.1.0) lib/sentry/rails/tracing.rb:54:in `instrument'
  from activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
  from actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
  from actionpack (6.1.4.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
  from activerecord (6.1.4.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (6.1.4.6) lib/abstract_controller/base.rb:165:in `process'
  from actionview (6.1.4.6) lib/action_view/rendering.rb:39:in `process'
  from actionpack (6.1.4.6) lib/action_controller/metal.rb:190:in `dispatch'
  from actionpack (6.1.4.6) lib/action_controller/metal.rb:254:in `dispatch'
  from actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  from actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  from actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
  from actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #7032.
Fixes #7318.

### CODE REVIEW

File: lib/active_admin/resource_controller/streaming.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@ def stream_resource(&block)
         headers["Last-Modified"] = Time.current.httpdate
 
         if ActiveAdmin.application.disable_streaming_in.include? Rails.env
-          self.response_body = block[""]
+          self.response_body = block[String.new]
```
Comment (javierjulio) [inline lib/active_admin/resource_controller/streaming.rb:27]: Curious since I'm not familiar with `frozen_string_literal` usage, what difference does `String.new` have over what this did previously?

**Review by javierjulio — APPROVED** [review]

File: lib/active_admin/resource_controller/streaming.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply lib/active_admin/resource_controller/streaming.rb:27]: `String.new` or `+""` force the empty string they create to be mutable.

Comment (deivid-rodriguez) [reply lib/active_admin/resource_controller/streaming.rb:27]: While, in `frozen_string_literal: true` mode, `""` creates a frozen empty string.

**Comment by deivid-rodriguez** [comment]
Thanks @javierjulio!

File: lib/active_admin/resource_controller/streaming.rb (hunk 1 above)
Comment (javierjulio) [reply lib/active_admin/resource_controller/streaming.rb:27]: That makes sense now. Thanks David!
