### PR TITLE
multiple HTTP methods actions 

### LINKED ISSUE #4795: Error with using multiple http methods with page_action
I'm trying the following syntax:
```
  page_action :preview, method: [:get, :post] do
    @page_title = 'Preview and Compare Zones'
    render 'preview', layout: 'active_admin'
  end
```

And getting the following error:
```/usr/local/lib/ruby/gems/2.4.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/mapper.rb:328:in `check_part': Missing :controller key on routes definition, please check your routes. (ArgumentError)```

### PR DESCRIPTION
**Pull request by Fivell**
fixes #4795

### CODE REVIEW

File: lib/active_admin/router.rb [hunk 1]
```diff
@@ -97,7 +97,7 @@ def resource_routes(config)
           page = config.underscored_resource_name
           get "/#{page}" => "#{page}#index"
           config.page_actions.each do |action|
-            build_route.call action.http_verb, "/#{page}/#{action.name}" => "#{page}##{action.name}"
+            [*action.http_verb].each { |verb| build_route.call verb, "/#{page}/#{action.name}" => "#{page}##{action.name}"  }
```
Comment (timoschilling) [inline lib/active_admin/router.rb]: Please change `[*action.http_verb].each` to `Array.wrap` and use a `do` block

Comment (Fivell) [inline lib/active_admin/router.rb]: @timoschilling, done
