### PR TITLE
Avoid duplicate work when downloading CSV

### LINKED ISSUE #7334: on Download CSV find_collection method called twice
### Did you find a bug?

During index CSV request processing #find_collection code is called twice, so collection is fetched from SQL or another source one extra time for no reason.

### Expected behaviour

#find_collection code being called only once 

### Actual behaviour

 #find_collection code being called twice

### How to reproduce

Here's a bug report  
`active_admin_csv_double_find_collection_bug.rb`  
```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Use local changes or ActiveAdmin master.
  if ENV["ACTIVE_ADMIN_PATH"]
    gem "activeadmin", path: ENV["ACTIVE_ADMIN_PATH"], require: false
  else
    gem "activeadmin", github: "activeadmin/activeadmin", require: false
  end

  # Change Rails version if necessary.
  gem "rails", "6.1.4"

  gem "sprockets", "3.7.2"
  gem "sassc-rails", "2.1.2"
  gem "sqlite3", "1.4.2", platform: :mri
  gem "activerecord-jdbcsqlite3-adapter", "61.0", platform: :jruby
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :active_admin_comments, force: true do |_t|
  end

  create_table :users, force: true do |t|
    t.string :full_name
  end
end

require "action_controller/railtie"
require "action_view/railtie"
require "active_admin"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.eager_load = false
  config.logger = Logger.new($stdout)

  config.hosts = "www.example.com"
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class User < ActiveRecord::Base
end

class TestSpy
  attr_reader :count

  def initialize
    @count = 0
  end

  def increment
    @count += 1
  end

  def reset
    @count = 0
  end
end
TEST_SPY = TestSpy.new

ActiveAdmin.setup do |config|
  # Authentication disabled by default. Override if necessary.
  config.authentication_method = false
  config.current_user_method = false
end

Rails.application.initialize!

ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }
  content do
    "Test Me"
  end
end

ActiveAdmin.register User do
  actions :index

  controller do
    def find_collection(*)
      TEST_SPY.increment
      # Rails.logger.debug { ">> FETCHING COLLECTION\n#{caller.join("\n")}" }
      super
    end
  end
end

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
end

require "minitest/autorun"
require "rack/test"
require "rails/test_help"

# Replace this with the code necessary to make your test fail.
class BugTest < ActionDispatch::IntegrationTest
  def test_csv_fetches_collection_once
    user = User.create! full_name: 'John Doe'
    TEST_SPY.reset
    get admin_users_url(format: :csv)
    csv_response_body = response.body.delete('﻿')
    assert_equal "Id,Full name\n#{user.id},John Doe\n", csv_response_body
    assert_response :success
    assert_equal 1, TEST_SPY.count
  end

  def test_html_fetches_collection_once
    User.create! full_name: 'John Doe'
    TEST_SPY.reset
    get admin_users_url
    assert_match /John Doe/, response.body
    assert_response :success
    assert_equal 1, TEST_SPY.count
  end

  private

  def app
    Rails.application
  end
end
```

Here's output log
```
$ ruby active_admin_csv_double_find_collection_bug.rb
Fetching https://github.com/activeadmin/activeadmin.git
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using minitest 5.15.0
Using zeitwerk 2.5.4
Using builder 3.2.4
Using i18n 1.10.0
Using tzinfo 2.0.4
Using erubi 1.10.0
Using activesupport 6.1.4
Using kaminari-core 1.2.2
Using globalid 1.0.0
Using activemodel 6.1.4
Using sqlite3 1.4.2
Using activerecord 6.1.4
Using rack 2.2.3
Using kaminari-activerecord 1.2.2
Using marcel 1.0.2
Using ruby2_keywords 0.0.5
Using method_source 1.0.0
Using thor 1.2.1
Using tilt 2.0.10
Using racc 1.6.0
Using nio4r 2.5.8
Using nokogiri 1.13.1 (x86_64-linux)
Using mini_mime 1.1.2
Using rails-dom-testing 2.0.3
Using mail 2.7.1
Using activejob 6.1.4
Using crass 1.0.6
Using ransack 2.5.0
Using loofah 2.14.0
Using rack-test 1.1.0
Using rails-html-sanitizer 1.4.2
Using sprockets 3.7.2
Using actionview 6.1.4
Using formtastic_i18n 0.7.0
Using ffi 1.15.5
Using actionpack 6.1.4
Using sassc 2.4.0
Using arbre 1.5.0
Using has_scope 0.8.0
Using railties 6.1.4
Using bundler 2.2.6
Using jquery-rails 4.4.0
Using activestorage 6.1.4
Using kaminari-actionview 1.2.2
Using actionmailbox 6.1.4
Using actiontext 6.1.4
Using actionmailer 6.1.4
Using kaminari 1.2.2
Using responders 3.0.1
Using formtastic 4.0.0
Using websocket-extensions 0.1.5
Using sprockets-rails 3.4.2
Using websocket-driver 0.7.5
Using inherited_resources 1.13.1
Using sassc-rails 2.1.2
Using actioncable 6.1.4
Using rails 6.1.4
Using activeadmin 2.10.0 from https://github.com/activeadmin/activeadmin.git (at master@23c0ecf)
-- create_table(:active_admin_comments, {:force=>true})
D, [2022-02-15T11:44:48.394759 #32043] DEBUG -- :    (0.4ms)  SELECT sqlite_version(*)
D, [2022-02-15T11:44:48.394993 #32043] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "active_admin_comments"
D, [2022-02-15T11:44:48.395195 #32043] DEBUG -- :    (0.1ms)  CREATE TABLE "active_admin_comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0033s
-- create_table(:users, {:force=>true})
D, [2022-02-15T11:44:48.395343 #32043] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "users"
D, [2022-02-15T11:44:48.395467 #32043] DEBUG -- :    (0.1ms)  CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "full_name" varchar)
   -> 0.0002s
D, [2022-02-15T11:44:48.408242 #32043] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2022-02-15T11:44:48.412389 #32043] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2022-02-15T11:44:48.414762 #32043] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2022-02-15T11:44:48.414899 #32043] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.0ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", "2022-02-15 09:44:48.414539"], ["updated_at", "2022-02-15 09:44:48.414539"]]
D, [2022-02-15T11:44:48.414996 #32043] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
Run options: --seed 60841

# Running:

D, [2022-02-15T11:44:48.790359 #32043] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
I, [2022-02-15T11:44:48.790429 #32043]  INFO -- : -----------------------------------------
I, [2022-02-15T11:44:48.790439 #32043]  INFO -- : BugTest: test_csv_fetches_collection_once
I, [2022-02-15T11:44:48.790446 #32043]  INFO -- : -----------------------------------------
D, [2022-02-15T11:44:48.792359 #32043] DEBUG -- :   TRANSACTION (0.0ms)  SAVEPOINT active_record_1
D, [2022-02-15T11:44:48.792467 #32043] DEBUG -- :   User Create (0.0ms)  INSERT INTO "users" ("full_name") VALUES (?)  [["full_name", "John Doe"]]
D, [2022-02-15T11:44:48.792580 #32043] DEBUG -- :   TRANSACTION (0.0ms)  RELEASE SAVEPOINT active_record_1
I, [2022-02-15T11:44:48.797456 #32043]  INFO -- : Started GET "/admin/users.csv" for 127.0.0.1 at 2022-02-15 11:44:48 +0200
I, [2022-02-15T11:44:48.804460 #32043]  INFO -- : Processing by Admin::UsersController#index as CSV
D, [2022-02-15T11:44:48.809576 #32043] DEBUG -- :    (0.1ms)  SELECT COUNT(*) FROM "users"
D, [2022-02-15T11:44:48.810175 #32043] DEBUG -- :   User Load (0.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" desc LIMIT ? OFFSET ?  [["LIMIT", 1000], ["OFFSET", 0]]
I, [2022-02-15T11:44:48.810342 #32043]  INFO -- : Completed 200 OK in 6ms (Allocations: 3365)


D, [2022-02-15T11:44:48.811422 #32043] DEBUG -- :   TRANSACTION (0.0ms)  rollback transaction
F

Failure:
BugTest#test_csv_fetches_collection_once [active_admin_csv_double_find_collection_bug.rb:121]:
Expected: 1
  Actual: 2


rails test active_admin_csv_double_find_collection_bug.rb:114

D, [2022-02-15T11:44:48.811838 #32043] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
I, [2022-02-15T11:44:48.811874 #32043]  INFO -- : ------------------------------------------
I, [2022-02-15T11:44:48.811883 #32043]  INFO -- : BugTest: test_html_fetches_collection_once
I, [2022-02-15T11:44:48.811890 #32043]  INFO -- : ------------------------------------------
D, [2022-02-15T11:44:48.812163 #32043] DEBUG -- :   TRANSACTION (0.0ms)  SAVEPOINT active_record_1
D, [2022-02-15T11:44:48.812257 #32043] DEBUG -- :   User Create (0.0ms)  INSERT INTO "users" ("full_name") VALUES (?)  [["full_name", "John Doe"]]
D, [2022-02-15T11:44:48.812345 #32043] DEBUG -- :   TRANSACTION (0.0ms)  RELEASE SAVEPOINT active_record_1
I, [2022-02-15T11:44:48.813161 #32043]  INFO -- : Started GET "/admin/users" for 127.0.0.1 at 2022-02-15 11:44:48 +0200
I, [2022-02-15T11:44:48.814069 #32043]  INFO -- : Processing by Admin::UsersController#index as HTML
D, [2022-02-15T11:44:48.815972 #32043] DEBUG -- :   Rendering /home/senid/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/app/views/active_admin/resource/index.html.arb
DEPRECATION WARNING: The asset "active_admin.css" is not present in the asset pipeline.
Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
 (called from block (2 levels) in build_active_admin_head at /home/senid/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/views/pages/base.rb:33)
DEPRECATION WARNING: The asset "active_admin.js" is not present in the asset pipeline.
Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
 (called from block (2 levels) in build_active_admin_head at /home/senid/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/views/pages/base.rb:42)
D, [2022-02-15T11:44:48.951752 #32043] DEBUG -- :   User Load (0.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" desc LIMIT ? OFFSET ?  [["LIMIT", 30], ["OFFSET", 0]]
I, [2022-02-15T11:44:48.957930 #32043]  INFO -- :   Rendered /home/senid/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/app/views/active_admin/resource/index.html.arb (Duration: 141.9ms | Allocations: 281318)
I, [2022-02-15T11:44:48.958042 #32043]  INFO -- : Completed 200 OK in 144ms (Views: 143.5ms | Allocations: 282604)


D, [2022-02-15T11:44:48.958647 #32043] DEBUG -- :   TRANSACTION (0.0ms)  rollback transaction
.

Finished in 0.169852s, 11.7750 runs/s, 41.2123 assertions/s.
2 runs, 7 assertions, 1 failures, 0 errors, 0 skips
```

If you comment out line `Rails.logger.debug { ">> FETCHING COLLECTION\n#{caller.join("\n")}" }`
You will see that first time #find_collection being called during #collection calculation
```
active_admin_csv_double_find_collection_bug.rb:98:in `find_collection'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/resource_controller/data_access.rb:45:in `collection'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/inherited_resources-1.13.1/lib/inherited_resources/actions.rb:7:in `index'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/resource_controller/streaming.rb:13:in `index'
```

And second time it being called directly in `ActiveAdmin::CSVBuilder#build` as `@collection = controller.send :find_collection, except: :pagination`
```
active_admin_csv_double_find_collection_bug.rb:98:in `find_collection'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/csv_builder.rb:46:in `build'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/resource_controller/streaming.rb:27:in `stream_resource'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/resource_controller/streaming.rb:40:in `stream_csv'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/resource_controller/streaming.rb:14:in `block (2 levels) in index'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/responders-3.0.1/lib/action_controller/responder.rb:238:in `default_render'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/responders-3.0.1/lib/action_controller/responder.rb:190:in `to_format'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/responders-3.0.1/lib/action_controller/responder.rb:165:in `respond'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/responders-3.0.1/lib/action_controller/responder.rb:158:in `call'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/responders-3.0.1/lib/action_controller/respond_with.rb:213:in `respond_with'
~/.rvm/gems/ruby-2.7.3@didww-rs/gems/inherited_resources-1.13.1/lib/inherited_resources/actions.rb:7:in `index'
~/.rvm/gems/ruby-2.7.3@didww-rs/bundler/gems/activeadmin-23c0ecff86a3/lib/active_admin/resource_controller/streaming.rb:13:in `index'
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #7334.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Not sure how to get this tested. Only cucumber features have the proper setup to get this tested, but cucumber features are not supposed to verify this low level stuff.

File: lib/active_admin/resource_controller/data_access.rb [hunk 1]
```diff
@@ -250,6 +250,8 @@ def current_scope
       end
 
       def apply_pagination(chain)
+        # skip pagination if CSV format was requested
```
Comment (Fivell) [inline lib/active_admin/resource_controller/data_access.rb:253]: @deivid-rodriguez, can you please clarify 

# return chain if params["format"] == "csv"

 so it should be commented out or not  ?

Comment (deivid-rodriguez) [reply lib/active_admin/resource_controller/data_access.rb:253]: Totally my bad. It should be uncommented. I think I left it commented out unintentionally while trying to write a failing test for this issue. I will fix it.

Comment (deivid-rodriguez) [reply lib/active_admin/resource_controller/data_access.rb:253]: I updated this!

**Comment by deivid-rodriguez** [comment]
In the end I made a bigger refactor that allowed things to be more easily unit tested.

**Comment by deivid-rodriguez** [comment]
Can you try this @senid231?

**Comment by deivid-rodriguez** [comment]
Let's try it!

File: lib/active_admin/csv_builder.rb [hunk 2]
```diff
@@ -43,7 +43,6 @@ def column(name, options = {}, &block)
     end
 
     def build(controller, csv)
-      @collection = controller.send :find_collection, except: :pagination
```
Comment (rylanb) [inline lib/active_admin/csv_builder.rb:46]: As a note, this maybe a 'private' part of the gem, but this broke an admin view for us. I can't find a way to get at the collection for a CSV download now. Any tips would be appreciated! 

This refactor looks nice, otherwise!

Comment (deivid-rodriguez) [reply lib/active_admin/csv_builder.rb:46]: Can you show an example of what broke, ideally a public repository, and instructions to reproduce the problem. Thanks!

Comment (deivid-rodriguez) [reply lib/active_admin/csv_builder.rb:46]: `controller.send :find_collection, except: :pagination`?

Comment (rylanb) [reply lib/active_admin/csv_builder.rb:46]: Great that seems to have worked! I should have tried that first, but was trying to avoid firing another query. 

Thanks so much! 

For posterity: `first_item = controller.send(:find_collection, except: :pagination).first` worked to fix up this code. Thanks!

Comment (deivid-rodriguez) [reply lib/active_admin/csv_builder.rb:46]: Maybe `first_item = controller.send(:collection).first` works for you to avoid to extra query.

Comment (rylanb) [reply lib/active_admin/csv_builder.rb:46]: I tried that out but ended up switching to `controller.public_send(:find_collection ...` as we override that in the admin class already. Thanks!
