### PR TITLE
skip polymorphic associations when detecting class in active filters

### LINKED ISSUE #5027: Filters don't work with a polymorphic model both type and id set
### Expected behavior

In 1.0 I could define a filter for each field that makes up a polymorphic relation, provide values for both filter fields and it works as expected.

```ruby
  filter :commentable_type
  filter :commentable_id, label: "Commentable Id"
```

This though on master is now failing when **you provide a value for both fields**. If you omit a value for the commentable_id field the filter works fine. No error.

The error occurs due to changes to the active filters that is displayed in the sidebar. Since its trying to display what is being filtered, it thinks the field is a constant so I'm seeing an error of: `uninitialized constant Commentable` when submitting a filter value for both fields.

### How to reproduce

I have a [sample app that reproduces the error](https://github.com/javierjulio/activeadmin-filters-error). Do the following:

- clone project
- run `bundle install && rails db:setup` (dummy data is seeded)
- `rails s`
- go to http://localhost:3000/admin/comments
- set a filter for commentable_type, run it, it works
- set a filter for commentable_id and commentable_type, submit and it fails.

The error that appears is:

```
uninitialized constant Commentable
```

Stacktrace:

```
activesupport (5.0.4) lib/active_support/inflector/methods.rb:268:in `const_get'
activesupport (5.0.4) lib/active_support/inflector/methods.rb:268:in `block in constantize'
activesupport (5.0.4) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.4) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.4) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.4) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active_filter.rb:70:in `find_class'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active_filter.rb:16:in `initialize'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active.rb:21:in `new'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active.rb:21:in `block in build_filters'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active.rb:21:in `map'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active.rb:21:in `build_filters'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active.rb:15:in `initialize'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active_sidebar.rb:13:in `new'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/filters/active_sidebar.rb:13:in `block in block'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/components/sidebar_section.rb:25:in `instance_exec'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/components/sidebar_section.rb:25:in `build_sidebar_content'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/components/sidebar_section.rb:13:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `sidebar_section'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:132:in `block (2 levels) in build_sidebar'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:131:in `collect'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:131:in `block in build_sidebar'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:130:in `build_sidebar'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:78:in `block in build_page_content'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:76:in `build_page_content'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:50:in `block in build_page'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:49:in `build_page'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/app/views/active_admin/resource/index.html.arb:2:in `block in ___sers_javierjulio__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin_____a_deeedf_app_views_active_admin_resource_index_html_arb___2449977813835396574_70183135983860'
arbre (1.1.1) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.1.1) lib/arbre/context.rb:45:in `initialize'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/app/views/active_admin/resource/index.html.arb:1:in `new'
/Users/javierjulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-8541a5deeedf/app/views/active_admin/resource/index.html.arb:1:in `___sers_javierjulio__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin_____a_deeedf_app_views_active_admin_resource_index_html_arb___2449977813835396574_70183135983860'
actionview (5.0.4) lib/action_view/template.rb:159:in `block in render'
```

### PR DESCRIPTION
**Pull request by Fivell**
[fixes #5027]

### CODE REVIEW

**Comment by Fivell** [comment]
@javierjulio , unfortunately there is no polymorphic stuff in our test models, can you please check it by hand ?

File: lib/active_admin/filters/active_filter.rb [hunk 1]
```diff
@@ -66,7 +66,8 @@ def find_class
         if condition_attribute.klass != resource_class && condition_attribute.klass.primary_key == name.to_s
           condition_attribute.klass
         else
-          assoc = condition_attribute.klass.reflect_on_all_associations.detect { |r| r.foreign_key.to_s == name.to_s }
+          assoc = condition_attribute.klass.reflect_on_all_associations.
+            detect { |r| r.foreign_key.to_s == name.to_s && !r.options[:polymorphic] } #skip polymorphic
```
Comment (javierjulio) [inline lib/active_admin/filters/active_filter.rb]: Since we have the comment here I think we could improve it by making the code more explicit/readable. Would something like the below work? What do you think? Not critical so I leave it up to you.

```ruby
assoc = condition_attribute.klass.reflect_on_all_associations.
  reject { |r| r.options[:polymorphic] }.
  detect { |r| r.foreign_key.to_s == name.to_s }
```

**Comment by javierjulio** [comment]
Haha I was suggesting the code change so we could remove the skip polymorphic comment, sorry about the confusion. Either way it works well, thanks!
